apiVersion: v1
kind: Service
metadata:
  name: bandwagon
  namespace: kube-system
  labels:
    app: bandwagon
spec:
  selector:
    app: bandwagon
  ports:
    - port: 80
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bandwagon
  namespace: kube-system
  labels:
    app: bandwagon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bandwagon
  nodeSelector:
    gravitational.io/k8s-role: master
  template:
    metadata:
      labels:
        app: bandwagon
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: docker/default
    spec:
      tolerations:
        - key: "gravitational.io/runlevel"
          value: system
          operator: Equal
          # allows to run on master nodes
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
      securityContext:
        runAsUser: -1
      nodeSelector:
        gravitational.io/k8s-role: master
      containers:
        - name: bandwagon
          image: bandwagon:0.0.0
          ports:
            - containerPort: 8000
          env:
            - name: PATH
              value: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: bin
              mountPath: /opt/bin
            - name: gravity
              mountPath: /var/lib/gravity/local
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: bin
          hostPath:
            path: /usr/bin
        - name: gravity
          hostPath:
            path: /var/lib/gravity/local
        - name: tmp
          hostPath:
            path: /tmp
